### ISSUE TITLE
dkms fails to build on Kernel Version 5.19

### ISSUE THREAD

**Issue by EndlessEden** [Woomy4680-exe/RTL88x2BU-Debian#5]
### Distribution: Debian 11

-----

during module build, a error is thrown.

> rtl88x2bu/1.0.0/build/os_dep/osdep_service.c:1312:2: error: implicit declaration of function 'complete_and_exit' [-Werror=implicit-function-declaration] 

there is also a few "-Werror=incompatible-pointer-types" errors thrown later.
